CREATE DATABASE demo_db;
USE demo_db;

DROP TABLE IF EXISTS demo_table;
CREATE TABLE IF NOT EXISTS demo_table
(
  uid  INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  key1 VARCHAR(255) NOT NULL DEFAULT '',
  key2 VARCHAR(255) NOT NULL DEFAULT '',
  some_date DATE NOT NULL DEFAULT '1970-01-01',
  some_datetime DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
