import { Component, Prop, Watch, Model } from 'vue-property-decorator'

import './assets'
import './Vue+extends'
export * from './ViewController'
export * from './FragmentProtocol'
export * from './pickers'
export * from './i18n'
export * from './dialogs'
export * from './widgets'
export * from './drawers'
export * from './tables'
export * from './sidebars'
export * from './loading'
export * from './layouts'
export * from './diff'
export * from './RootView'
export { Component, Prop, Watch, Model }
