# CREATE DATABASE `demo_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP TABLE IF EXISTS demo_table;
CREATE TABLE IF NOT EXISTS demo_table
(
    uid           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    key1          VARCHAR(127)    NOT NULL DEFAULT '',
    key2          VARCHAR(127)    NOT NULL DEFAULT '',
    some_date     TIMESTAMP       NULL,
    some_datetime DATETIME        NULL,
    create_time   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS demo_table_2;
CREATE TABLE IF NOT EXISTS demo_table_2
(
    uid         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    key1        VARCHAR(127)    NOT NULL DEFAULT '',
    key2        VARCHAR(127)    NOT NULL DEFAULT '',
    create_time TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS demo_table_3;
CREATE TABLE IF NOT EXISTS demo_table_3
(
    uid         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    key1        VARCHAR(127)    NOT NULL DEFAULT '',
    `key`       VARCHAR(127)    NOT NULL DEFAULT '',
    create_time TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;
